### ISSUE TITLE
Guides > Backoffice > How to add template Workspace app

### ISSUE THREAD

**Issue by w-le** [PlaceOS/docs#101]
1. What are the prerequisites (Domains and Oauth Applications, staff api Tenant, sso)
2. How to add placeos/user-interfaces workplace frontend app
3. What Zone metadata and tags are REQUIRED
4. What optional Zone metadata exists and how does it affect he workplace frontend

**Comment by jeremyw24** [comment]
How to add an application is in progress: https://github.com/PlaceOS/docs/blob/placeos-api-auth/how-to/backoffice/add-application.md

Currently has a PR open: https://github.com/PlaceOS/docs/pull/93

@w-le please feel free to contribute/elaborate on the above.

**Comment by jeremyw24** [comment]
Probably also ties into this branch with PR: https://github.com/PlaceOS/docs/pull/97

I am currently working on this, but also welcome contributions.
