### ISSUE TITLE
More detailed documentation for basic PlaceOS REST API

### ISSUE THREAD

**Issue by w-le** [PlaceOS/docs#125]
Currently on docs.placeos.com the PlaceOS REST API documentation is just this page:
![image](https://user-images.githubusercontent.com/10395560/152723649-159c4f24-75f7-4dc4-aebe-1ee72f1e06bc.png)

Which links to this APIary which ONLY has the Zones and Systems requests:
https://placeos.docs.apiary.io/#reference
![image](https://user-images.githubusercontent.com/10395560/152723728-24620dd1-7c72-4fd9-beb8-117b16a77bb1.png)

Can we get an available team member to port over the much much better and more complete ACAEngine API docs (which I believe Kim wrote), which can be found here: https://engine.place.technology/api/control/modules

**Comment by jeremyw24** [comment]
@w-le sure, we have been waiting for the automatically generated OpenAPI Spec from PlaceOs to solve this problem.

**Comment by w-le** [comment]
looks like this is being escalated by clients and partners
hey @jeremyw24 can we assign a product team member for a couple days to copy/paste the already excellent [acaengine rest api docs](https://engine.place.technology/api/control/systems) and change them where required to suit placeos? that would be a really great starting point and solve almost all the current paint points.

**Comment by w-le** [comment]
Jeremy has moved the docs here and improved them significantly (thanks to advice from Steve): https://docs.placeos.com/reference/rest-api

Many api endpints are still not documented yet, but will become documented upon completion of https://github.com/PlaceOS/rest-api/issues/251
