### ISSUE TITLE
Proofread action not working

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs#18]
There looks to have been a change in some of the actions payload formats that has knocked the proofreader offline. Issue is in the place-labs/orthograph-err#4. Tracking here for impact on this repo.

**Comment by kimburgess** [comment]
This back up and running now.

@mghill there's a couple of PR's that are stuck in an inconsistent state with the checks status. The simplest way to resolve will be to close the PR and reopen. Given these all appear to be notes based content which will need some massaging into doc format I'll close them off then leave it to you to reopen as the associate doc is worked on and ready for review.

**Comment by mghill** [comment]
Good call. I might make an issue to go through @stakach 's branches and collate them into consistent docs. So best leave the PRs closed until I have manually combed through the branches. Good to know checks should run correctly now. They only run when pulling to Main, right?

**Comment by kimburgess** [comment]
Yep correct, although this can be enabled for other branches too if that's of use.

I've also changed the required checks to only include:
1. no-empty-section
2. no-exclamation-question-mark
3. once-sentence-per-line
4. period-in-list-item
5. spelling

These seem to form the non-subjective set rules. All others will still annotate the commit with suggestions, but not block a merge.

**Comment by kimburgess** [comment]
Reopening. The check status has not applied correctly in https://github.com/PlaceOS/docs/pull/22/checks?check_run_id=1445826152#step:3:28.

**Comment by kimburgess** [comment]
Finally got to the bottom of this! GitHub expects the annotations to appear on the head commit sha within a PR, which is _not_ the same as the commit sha that the actions framework passes through.

Working a little neater now, with the bonus of some additional logging and human-readable output ([example](https://github.com/PlaceOS/docs/pull/22/checks?check_run_id=1447102894#step:3:23)) in place for helping with future tooling improvements.
