### ISSUE TITLE
Configuring PlaceOS for SAML Auth

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/docs#21]
https://docs.google.com/document/d/12lCTbqLP2QPg1Gbey9GWLMyDXLFJ6DyolPy65uBnW_c/edit#heading=h.snxcqt1425dd

**Comment by kimburgess** [comment]
Reopening this. It looks like information here may have been merged in a hurry.

The content currently in [`how-to/authentication/`](https://github.com/PlaceOS/docs/tree/main/how-to/authentication) contains a lot of errors in both language and technical details. IMO it should not have published in the state, but it's there no so the best path of action is spend some time reviewing, and forming into something more fit for human consumption.

It may be possible to also condense some of the different variations that provide detail for common IdP's into a set of [tab groups](https://github.com/PlaceOS/docs#tabs) within the one doc. This should also help with keeping the process a little more easy to follow for readers.

I have excluded this from linting in https://github.com/PlaceOS/docs/pull/73/commits/6cf62c45bb09c7a64964b677c79211aacc45a324 until this can be addressed.
