### ISSUE TITLE
Asset migration & solution

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs#23]
- Migrate across required (preexisting) images and assets to embed into docs, 
- Source any glaringly missing assets (if any)
- Find/implement solutions for:
    - Flowcharts inline with text [like this](https://mermaid-js.github.io/mermaid/#/flowchart)
    - Feature demos, either stills, animated captures, or "live" simulations

Issue can be expanded as it is investigated, may require splitting if some parts are much more work.

**Comment by mghill** [comment]
Mermaid implementation tracked at https://github.com/PlaceOS/docs-site/issues/14

Site/file structure probably stable enough to support assets at this point without having to mess around with paths for embedding all the time

**Comment by mghill** [comment]
@KimBurgess for asset hosting, do you have a preference in where and how? My assumption is in the docs repo not docs-site (certainly for static images. For fancier web content that may have to be different?). And I assume the default would be an assets folder like [the previous docs site](https://github.com/acaengine/docs/tree/master/.gitbook/assets), but another option would be distributed into the folders that they are used in (so the embed link is just the filename, not a path to it). If you've got no preference, I'd go with how it was done before, but this is our best opportunity to change if need be.

**Comment by kimburgess** [comment]
Strong preference to use inline diagrams (https://github.com/PlaceOS/docs-site/issues/14) as the preferred source for visuals as this will allow appropriate styling for different outputs.

Where this isn't appropriate, keeping images (and other media) alongside markdown content within the directory tree where they are used will be the cleanest approach and prevent end endlessly growing list of assets with unclear uses.

```
|- example-doc.md
|- foo.jpg
```

This can then be shown using the [markdown inline image syntax](https://github.github.com/gfm/#images).

```markdown
![alt text](foo.jpg "Title text")
```

Any of these will be picked up by the site rendered, optimised and published along with the content. This will also render neatly when viewed directly on GitHub (and in some local editors too).

If media is shared between multiple documents, it should exist in the lowest common point of the directory tree.

**Comment by mghill** [comment]
That all makes sense, no surprises on any point. Mainly wanted a sanity check/check-in.
- Mermaid diagrams where possible
- Other media is distributed so that intended use is clear

This could mean a little bit of ongoing maintenance if the same image becomes needed elsewhere, but that's minor enough to not be a point against imo.

**Comment by mghill** [comment]
Given the resolution to have the file structure to be relatively flat, I think it might be worth having a media folder in each of the 4 buckets? Otherwise it will get pretty messy pretty quickly if each bucket just has all the `.md` files *and* all the images etc. Not totally set on a solution, but this one feels most normal

**Comment by kimburgess** [comment]
That sounds like a good idea to help keep things neat. These (and any other assets) can be placed anywhere that makes sense here. The only important point is to ensure that they are linked or referenced using relative paths from the doc(s) that use them.

When the site builds these will be preprocessed (if appropriate for the file type), copied to `assets/` directory in the build output and any references pointed to this. Any non-linked assets are ignored. The output filenames are all based on a hash of the contents so no need to stress about conflicts there either.

**Comment by mghill** [comment]
That's good backend info to know. I'll go ahead with this and reassess if there turn out to be significant issues (which seems unlikely)
