### ISSUE TITLE
Linter incorrectly flags model numbers

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs#26]
Extending from https://github.com/PlaceOS/docs/pull/25#issuecomment-734502635.

Company and product names / model identifiers present an issue for accurate linting. In many cases these are intentionally misspelled words. Using directly exceptions may introduce an undesired side effect of also missing actual mistakes.

There's a few approaches here - issue it open for discussion.

**Comment by kimburgess** [comment]
One approach is to define a tagging semantic to explicitly denote these. A HTML element can be added inline with the appropriate metadata. This stays compliant with markdown, and does introduce any visual styling (like using emphasis, backticks and others would).

```markdown
As an example, we could mention <span class="org">Vandely Industries</span> and their <span class="model">Latex1000</span> product.
```

Some appropriate elements for this:
- [`data`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data)
- [`span`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span)

**Comment by kimburgess** [comment]
Another alternative: [`i` (idiomatic text element)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i) seems like an appropriate fit given it's current semantics. We can adjust styling so this still renders as normal text as markdown italics parse to `em` elements. This also has the advantage of less typing.

**Comment by mghill** [comment]
If we go with that solution, it could probably extend to cover #27 well enough: simply wrap any sections of text-like code (import statements etc) or blocks of JSX which are not automatically skipped by the linter. Rather than playing chasey with each thing we want to slip through, we can use `<i>` for anything that's one-off or too convoluted to filter.

**Comment by mghill** [comment]
Playing around with it, wrapping with `<i>` tags works so long as it is a multiline section. Perfect for code blocks or large chunks of text etc, and the parser would only need a change to be able to process it inline.

Example of what works: 

```
<i>
Model br89-i is recommended

import tablename from path/.filename
</i>
```

Example of what doesn't:
```
If you want to talk about <i> VariableName </i> in the middle of a sentence

Or even if you single out
<i>
Terminologie unusuelle
</i> 
onto its own lines without a double break
```

**Comment by kimburgess** [comment]
The linter exceptions will _not_ be setup for this at the moment. Just spitballing ideas to define the best approach before jumping to implementation.

On usage, `i` is an inline element so correct usage would be:
```markdown
Model <i>br89-i</i> is recommended.
```

For the MDX parsing (#27) see comments over there. Keen to on your thoughts for the approach outlined and any limits you can see.

**Comment by kimburgess** [comment]
@PlaceOS/docs any objections to standardising on use the [`<i>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i) tags for this use case (organisation / manufacturer / model identifiers)?

They're definitely my preference as they encode correct semantics in the content while also using the most minimal syntax I can see. Unless theres loud noises here, I'll adjust the grammar bot to suit.

**Comment by mghill** [comment]
Yeah, strongly approve. It's a good solution.
