### ISSUE TITLE
Linter: ignore spelling in link titles when URL contains term

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs#30]
Link titles should not flag spelling errors for terms contained with the link itself.

This will avoid having to designate as idiomatic terms, or specify additional markup for clearly correct references.

**Comment by mghill** [comment]
An implementation was added to the linter in https://github.com/PlaceOS/docs/commit/9fc55fcabb72311afe9ade60f1d2d086af7ed7b2 

It uses `/\[(.*)\]\(.*\1.*\)/i` which only works if the entirety of the link text occurs at least once in the link itself. I tried other variations which got messy quickly. At a few passes, this works and can be amended later if a smarter use is required.

**Comment by kimburgess** [comment]
Awesome. That works for now.

The limitation where it will skip `[example](https://example.com)`, but not `[this is a link to example](https://example.com)` will definitely be an annoyance at some point.

The [current spellchecker](https://github.com/tani/textlint-rule-spelling) tokenises words and checks each of these individually. Unfortunately it only checks skip patterns across the node local node (in this case, the link title), but does not pass any of the outer context (e.g. the full link object with uri). From a quick browse of the internals it's a little rough - not sure if its the best way to direct effort for any modifications to support this.

There's a more well structured alternative—[texlint-rule-spellchecker](https://github.com/textlint-rule/textlint-rule-spellchecker)—which may be good to switch to instead and focus attention on when required. Unfortunately it has it's own set of issues: namely [it uses the system default dictionary](https://github.com/textlint-rule/textlint-rule-spellchecker/issues/56), which will need to be solved first. When the annoyance outweighs the effort to add support for this we can look to transition and solve this more generally too.

**Comment by mghill** [comment]
Yeah, I had a look at textlint rules at the start, and had the same path of "oh good. Wait, no. Ehhh.... maybe" regarding textlint-rule-spellchecker. I don't think it's totally worth the switch at this point.

On the OP, in that same branch I've upgraded it to be a bit more generous with `/(\[.*\W|\[)(.+)(\W.*\]|\])\(.*\2.*\)/i` which will skip the whole thing if one of the whole words in the link text also appears anywhere in the url. It's perhaps a little greedy, but with that knowledge it can be manually treated with slightly more care.

This will (and should) skip:
```
[foo](www.foo.com)
[link to foo](www.foo.com)
[foo website](www.foobar.com)
[Foo-Files](www.foo.com)
```

It will (and shouldn't) skip:
```
[unintentional inclusions like o.c.](www.foo.com)
[word other than foo spelled incorrenctelly](foo.com)
```
It won't (and shouldn't?) skip:
```
[compoundwords](foo.com/compound)
[unrelated link text](foo.com)
```

**Comment by kimburgess** [comment]
Anything with this approach will be a hack, but that's a much nicer hack.

You could simplify it a little and also add a minimum length filter which will stop that short substring matching
```regex
/\[(.*\W)?(\w+)(\W.{4,})?\]\(.*\2.*\)/i
```
https://regex101.com/r/4wqe4m/1/
