### ISSUE TITLE
Language style guide

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs#37]
From https://github.com/place-labs/orthograph-err/issues/8#issue-755735912

> A lot of the current phase of customizing Orthograph-err is in finding & detailing specific exceptions. I foresee future stages involving higher/broader decisions such as consistent use of second person or title case, which are the typical jurisdiction of style guides. Textlint supports rule-presets which could be useful in both of these cases, or at least could be implemented alongside a full style guide as a fallback.
>
> For example, google has a style guide for technical documentation which has a community-implemented textlint-rule-preset
https://github.com/textlint-rule/textlint-rule-preset-google
and
https://developers.google.com/style
—@mghill

**Comment by mghill** [comment]
Most of our writing is in line with Google's with some enforcement via Orthograph-err (including anywhere we really deviate from it). This hasn't been formalised at this point in any real capacity though
