### ISSUE TITLE
RFC: deprecate the usage of rousseau?

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs#49]
[Rousseau](https://github.com/GitbookIO/rousseau) is currently used as part of the automated proofreading, however [most checks are disabled](https://github.com/PlaceOS/docs/blob/f09c6633b4032bdd9a0340b4a7985443ed706478/.textlintrc#L27-L33) due to duplication with other tools. It does not appear to be actively maintained and has a number of security advisories associated with upstream deps which would be good to either resolve, or prevent from pollution tooling used here.

The currently enabled checks are:
1. `simplicity`, which is a basic set of [suggested replacements using these rules](https://github.com/GitbookIO/rousseau/blob/master/lib/en/data/simpler.js), and
2. `readability`, which implements an [automated readability index](https://en.wikipedia.org/wiki/Automated_readability_index).

@mghill are either of these providing useful feedback? If not, a simple fix is to drop its usage. If yes, can look at patching upstream, or re-implementing these as standalone textlint rules.

**Comment by mghill** [comment]
The overlap with Write-good is strong, and anything else can probably be done by a tool designed to do it better. 
Something that addresses this remaining "complexity evaluation" role would be good though. Simplicity is conceptually useful, to highlight vocab which would make the docs harder to read (and is easy to subconsciously use), but the scope of Rousseau's implementation is pretty narrow (_Edit to add: Write-good also has a "wordy or unneeded" list which serves a the same purpose_). Similarly, some readability measure (either sentence to sentence or doc-wide) is useful as a general guide/flag for any sections that get carried away in prose (like this).
