### ISSUE TITLE
Reference > Spec Runner

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/docs#64]
Document the features, purpose and use of the PlaceOS Spec Runner tool.

**Comment by mghill** [comment]
Any links or starting info? Who is the contact/expert on this?

**Comment by jeremyw24** [comment]
@mghill its just in the backlog for now, but I think Steve or Kim would be best to consult regarding the spec runner.

**Comment by mghill** [comment]
Legit. Happy to flesh issues out once they're towards the front of the queue
