### ISSUE TITLE
Steps to add a Domain

### ISSUE THREAD

**Issue by viv-4** [PlaceOS/docs#67]
# Add a domain to PlaceOS

1. Log in to Backoffice on the domain created during deployment. eg. https://1.2.3.4.xip.io/backoffice/
2. Domains tab (left menu) `+` to Add Domain
  - Name: `placeos.domain.com` (can be anything to identify the domain, usually the domain itself makes most sense)
  - Domain: `placeos.domain.com`
  - Login URL: `/login?continue={{url}}`
  - Logout URL: `/auth/logout`
3. Select the newly created Domain -> Applications -> New Application
  - Name: `Backoffice`
  - Scopes: leave blank
  - Skip Authorization: `true`
  - Login URL: `https://placeos.domain.com/backoffice/oauth-resp.html`
4. Users tab `+` to Add User
  - Domain: Select the domain created in step 2
  - First and Last name are required
  - Email: This will be the username (can be any valid email string)
  - System Admin: `true`

You can now login with the new user on the new domain.

**Comment by camreeves** [comment]
I've just added a PR for this one. Will wait for the review before updating this issue.

**Comment by viv-4** [comment]
https://github.com/PlaceOS/docs/pull/88
