### ISSUE TITLE
Document SAML for Okta Process

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/docs#82]
Put together instructions on configuring Okta for PlaceOS SAML Auth.

**Comment by viv-4** [comment]
I don't have access to an Okta environment to test this. Do we have one?

**Comment by jeremyw24** [comment]
@viv-4 no but I am sure we could spin one up, I thought you might remember from doing it for UoA and Newcastle.

**Comment by viv-4** [comment]
Ah no I didn't do the OKTA side of those, just the PlaceOS side

**Comment by viv-4** [comment]
So from the PlaceOS point of view OKTA functions largely the same as Azure, details on Issuer and IDP Target URL added for both in https://github.com/PlaceOS/docs/pull/95
